// 신규 사업소 생성 시 사용할 초기 데이터 템플릿을 한 곳에서 관리합니다.
// - store.js의 하드코딩을 줄이고, 향후 템플릿 변경을 이 파일에서만 하도록 분리

// 타임라인 기본 템플릿 (초기화 상태)
// - status: pending
// - start/completion/completed* 값은 null
export const getNewSiteTimelineTemplate = () => [
  // 1. 구축 및 설치
  // 1-1. 사전 준비
  {
    step: '1-01',
    task: 'Kick-Off',
    section: '구축 및 설치',
    subsection: '사전 준비',
    status: 'pending',
    role: 'both',
  },
  {
    step: '1-02',
    task: '현장 답사시 비콘 갯수 픽스',
    section: '구축 및 설치',
    subsection: '사전 준비',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-03',
    task: '비콘 번호 체계표 생성 및 비콘 개발사에 전달',
    section: '구축 및 설치',
    subsection: '사전 준비',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-04',
    task: '계약 FIX 되면 운영 서버 개발사에 개발 요청',
    section: '구축 및 설치',
    subsection: '사전 준비',
    status: 'pending',
    role: 'rnd',
  },
  {
    step: '1-05',
    task: '제품 발주',
    section: '구축 및 설치',
    subsection: '사전 준비',
    status: 'pending',
    role: 'field',
  },
  // 1-2. 인프라 구축
  {
    step: '1-06',
    task: 'IP 할당 및 구축',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-07',
    task: '포트포워딩',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-08',
    task: '중계기 설치 실사 동행 및 송수신 통신 테스트',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-09',
    task: '중계기 세팅',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-10',
    task: '중계기 음영지역 테스트',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-11',
    task: '중계기 방폭존 잔여 설치 공사',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-12',
    task: 'VPN 세팅',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-13',
    task: 'Lora 네트워크 서버 현장 서버실 설치',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-14',
    task: '통신 품질테스트',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-15',
    task: '중계기 품질 측정',
    section: '구축 및 설치',
    subsection: '인프라 구축',
    status: 'pending',
    role: 'field',
  },
  // 1-3. 가스검침기 설치
  {
    step: '1-16',
    task: 'PPM 고정가스 검침기 설치용 AP 셋팅을 위한 전송 서버 주소 및 고유 아이디 생성 및 배포',
    section: '구축 및 설치',
    subsection: '가스검침기 설치',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-17',
    task: 'PPM 고정가스 검침기 설치',
    section: '구축 및 설치',
    subsection: '가스검침기 설치',
    status: 'pending',
    role: 'field',
  },
  // 1-4. 운영서버 설치
  {
    step: '1-18',
    task: '알리고 API 신규 사업소 IP 등록',
    section: '구축 및 설치',
    subsection: '운영서버 설치',
    status: 'pending',
    role: 'rnd',
  },
  {
    step: '1-19',
    task: '운영서버 준비 완료 확인',
    section: '구축 및 설치',
    subsection: '운영서버 설치',
    status: 'pending',
    role: 'rnd',
  },
  {
    step: '1-20',
    task: '운영서버 현장 서버실 설치',
    section: '구축 및 설치',
    subsection: '운영서버 설치',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-21',
    task: '운영서버 URL 확인',
    section: '구축 및 설치',
    subsection: '운영서버 설치',
    status: 'pending',
    role: 'field',
  },
  // 1-5. 운영서버 설정
  {
    step: '1-22',
    task: '운영서버 권한 설정',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-23',
    task: '운영서버 사용자 설정',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-24',
    task: '운영서버 데이터 정책 관리 설정',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-25',
    task: '지자체 로고 파일 준비',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'rnd',
  },
  {
    step: '1-26',
    task: '트래커 EUI LIST 확인',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-27',
    task: '운영서버 운영사 관리 설정',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-28',
    task: '운영서버 센서 공급사 설정',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-29',
    task: '운영서버 센서 마스터 관리 설정',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-30',
    task: '운영서버 현장-센서 권한 관리 설정',
    section: '구축 및 설치',
    subsection: '운영서버 설정',
    status: 'pending',
    role: 'field',
  },
  // 1-6. 운영서버 데이터 등록
  {
    step: '1-31',
    task: '현장 관리 - 도면 세팅',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'rnd',
  },
  {
    step: '1-32',
    task: '현장 관리 - 현장 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-33',
    task: '비콘 관리 - 비콘 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-34',
    task: '트래커 관리 - 트래커 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-35',
    task: '이동형중계기 관리 - 이동형중계기 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-36',
    task: '센서 관리 - 워치 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-37',
    task: '센서 관리 - 이동가스검침기 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-38',
    task: '알림 관리 - 알림 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-39',
    task: '작업자 관리 - 작업자 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-40',
    task: '작업자 관리 - 트래커/센서 교부',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-41',
    task: '위험성 평가 관리 - 위험성 평가 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-42',
    task: '작업 관리 - 작업 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-43',
    task: '증빙자료 관리 - 증빙자료 13항 카테고리 등록',
    section: '구축 및 설치',
    subsection: '운영서버 데이터 등록',
    status: 'pending',
    role: 'rnd',
  },
  // 1-7. 현장 설치
  {
    step: '1-44',
    task: '비콘 설치',
    section: '구축 및 설치',
    subsection: '현장 설치',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-45',
    task: '지오 펜스 & 셀 플래닝',
    section: '구축 및 설치',
    subsection: '현장 설치',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-46',
    task: '트래커 스마트 워치 MAC 매핑',
    section: '구축 및 설치',
    subsection: '현장 설치',
    status: 'pending',
    role: 'field',
  },
  {
    step: '1-47',
    task: '스마트 워치 APP 설치',
    section: '구축 및 설치',
    subsection: '현장 설치',
    status: 'pending',
    role: 'field',
  },

  // 2. 대시보드 필드 테스트
  {
    step: '2-01',
    task: '사업소 명 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-02',
    task: '날짜 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-03',
    task: '날씨 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-04',
    task: '작업자 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-05',
    task: '작업 목록 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-06',
    task: '고정형 비콘 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-07',
    task: '트래커 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-08',
    task: '워치 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-09',
    task: '이동형 가스검침기 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-10',
    task: '이동형 중계기 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-11',
    task: '고정가스 검침기 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-12',
    task: '배터리 및 상태 이상 IoT 센서 현황 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '2-13',
    task: '위급 상황 현황 데이터 확인',
    section: '대시보드 필드 테스트',
    subsection: null,
    status: 'pending',
    role: 'both',
  },

  // 3. 준공 및 문서
  {
    step: '3-01',
    task: '현장 VOC 점검 리스트 확인',
    section: '준공 및 문서',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
  {
    step: '3-02',
    task: '메뉴얼 문서 작업',
    section: '준공 및 문서',
    subsection: null,
    status: 'pending',
    role: 'field',
  },
  {
    step: '3-03',
    task: '준공 문서 제출',
    section: '준공 및 문서',
    subsection: null,
    status: 'pending',
    role: 'field',
  },
  {
    step: '3-04',
    task: 'H/W, S/W 제품 사용 교육',
    section: '준공 및 문서',
    subsection: null,
    status: 'pending',
    role: 'field',
  },
  {
    step: '3-05',
    task: '사업소에 제품 배포 및 수량 확인',
    section: '준공 및 문서',
    subsection: null,
    status: 'pending',
    role: 'field',
  },
  {
    step: '3-06',
    task: '준공 검수',
    section: '준공 및 문서',
    subsection: null,
    status: 'pending',
    role: 'field',
  },
  {
    step: '3-07',
    task: '준공 완료',
    section: '준공 및 문서',
    subsection: null,
    status: 'pending',
    role: 'both',
  },
];

// 체크리스트 기본 템플릿 (초기화 상태: 전부 unchecked)
export const getNewSiteChecklistTemplate = () => [
  {
    text: '위급상황(심박위험, 유해가스위험, SOS신호), 위험작업(위험 작업), 현재 작업자 현황(잔류 작업자 수, 전체 입실자 수, 전체 퇴실자 수)',
    checked: false,
  },
  {
    text: '작업자가 트래커를 착용해서 위치비콘이 설치된 곳에 위치하면 대시보드에 착용자의 위치가 출력되는가',
    checked: false,
  },
  {
    text: '작업자의 이름, 위치, 심박수, 가스정보(이동형 가스검지기) 등 데이터가 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '작업자목록에서 작업자의 행을 클릭하였을 때 작업자의 동선이력이 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '배터리 및 상태 이상 IoT 센서 현황으로 장비명(IoT 센서로 명칭 그룹화), 위치, 배터리가 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '위급상황 현황으로 작업자, 위치, 위급상황, 발생시간이 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '작업목록에서 작업명, 위험도, 위치, 작업자 수, 작업예정일시 및 시작일시, 작업종료일시 작업상태가 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '고정형비콘목록에서 비콘 이름, Major Minor, 위치, 배터리가 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '트래커목록에서 트래커 이름, 작업자명, 배터리, 사용여부, SOS-ON, 발생시간이 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '워치목록에서 워치 이름, 작업자명, 심박수, 배터리, 사용여부, 발생시간이 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '이동형 가스검지기 목록에서 가스센서 이름, 작업자명, 5종가스데이터(CO, CO2, H2S, O2, LEL), 배터리, 사용여부, 발생시간이 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '위치이력, 워치 및 가스센서 이력, 알림이력이 조회 및 백업 데이터로 엑셀파일 생성이 가능한가',
    checked: false,
  },
  {
    text: '위험 알림 발생 시(심박수, 유해가스 허용범위를 넘어설 경우,SOS 신호 등), 어느화면에서든 위험 알림 팝업이 출력되는가',
    checked: false,
  },
  {
    text: '위험 알림 발생 시 안전관리자의 스마트폰에 SOS 팝업 정보 문자 메세지가 자동 & 수동으로 전달되는가',
    checked: false,
  },
  {
    text: '운영서버에서 개인별로 매핑된 갤럭시 워치의 심박수를 최소,최대로 조절이 가능한가',
    checked: false,
  },
  {
    text: '입/퇴사자 발생시 작업자 계정 생성/삭제와 트래커, 갤럭시 워치, 휴대용 가스검지기가 매핑되는가',
    checked: false,
  },
  {
    text: '해당 위치에 설치된 고정형 가스검침기의 가스데이터(2종, O2와 H2S)가 대시보드에 출력되는가',
    checked: false,
  },
  {
    text: '고정형 가스 검지기에서 허용범위를 넘어설 경우 대시보드에 빨간색으로 위험신호로 표시가 되는가',
    checked: false,
  },
  {
    text: '고정형 가스 검지기에서 허용범위를 넘어설 경우 알림을 표시하고 관리자에게 문자로 전송되는가',
    checked: false,
  },
];

// DB insert용으로 공통 필드를 강제 (날짜/완료정보 null 처리)
export const normalizeNewSiteTimelineForDb = (timeline) =>
  timeline.map((item) => ({
    ...item,
    startDate: null,
    completionDate: null,
    completedAt: null,
    completedBy: null,
    status: item.status ?? 'pending',
  }));
